apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume
          name: teste-volume
    - name: node-container
      image: node:latest
      volumeMounts:
        - mountPath: /volume
          name: teste-volume
  volumes:
    - name: teste-volume
      hostPath:
        path: /home/teste-volume
        type: DirectoryOrCreate